x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: 6

services:
    tradeit.user_service.app:
        build:
            context: ./
            dockerfile: ./docker/etc/supervisor.d/php/Dockerfile.local
        image: tradeit
        container_name: tradeit.user_service.app
        env_file:
            - ./.env
        ports:
            - ${APP_PORT:-8000}:80
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        volumes:
            - ./:${WORKDIR}
            - ./vendor/:${WORKDIR}/vendor
        networks:
            - tradeit
        depends_on:
            - tradeit.user_service.pgsql
            - tradeit.user_service.redis
            - tradeit.user_service.minio

    tradeit.user_service.pgsql:
        image: 'postgres:${POSTGRES_VERSION:-17}-alpine'
        container_name: tradeit.user_service.db
        env_file:
            - ./.env
        ports:
            - ${FORWARD_DB_PORT:-5432}:5432
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - ${DB_VOLUME_LOCAL:-./database/postgres-data}:/var/lib/postgresql/data
        networks:
            - tradeit
        logging: *default-logging
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
            retries: 3
            timeout: 5s
        restart: unless-stopped
    tradeit.user_service.redis:
        container_name: tradeit.user_service.redis
        image: redis:alpine
        ports:
            - ${FORWARD_REDIS_PORT:-6379}:6379
        volumes:
            - ${REDIS_VOLUME_LOCAL:-./database/redis-data}:/data
        networks:
            - tradeit
        logging: *default-logging
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    tradeit.user_service.minio:
        container_name: tradeit.user_service.minio
        image: minio/minio:latest
        ports:
            - ${FORWARD_MINIO_PORT:-9000}:9000
            - ${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-sail}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
        volumes:
            - ${MINIO_VOLUME_LOCAL:-./storage/minio-data}:/data
        networks:
            - tradeit
        command: minio server /data/minio --console-address ":${FORWARD_MINIO_CONSOLE_PORT}"
        logging: *default-logging
        healthcheck:
            test:
                - CMD
                - curl
                - -f
                - http://localhost:${FORWARD_MINIO_PORT}/minio/health/live
            retries: 3
            timeout: 5s
  
    tradeit.user_service.horizon:
        image: tradeit
        container_name: tradeit.user_service.horizon
        env_file:
            - ./.env
        command: php /var/www/html/artisan horizon
        working_dir: ${WORKDIR}
        volumes:
            - ./:${WORKDIR}
            - ./vendor/:${WORKDIR}/vendor
        environment:
            - QUEUE_CONNECTION=redis
        depends_on:
            - tradeit.user_service.redis
            - tradeit.user_service.pgsql
        networks:
            - tradeit
        restart: unless-stopped
        logging: *default-logging
networks:
    tradeit:
        driver: bridge
